#!/usr/bin/env python
#-*- coding: utf-8 -*-

__all__ = ('KINDO_VERSION', 'KINDO_MIN_VERSION', 'KINDO_API_VERSION', 'KINDO_KI_VERSION', 'KINDO_DEFAULT_HUB_HOST')

KINDO_VERSION = 1.1
KINDO_MIN_VERSION = 1.1
KINDO_API_VERSION = 1
KINDO_KI_VERSION = 3
KINDO_DEFAULT_HUB_HOST = "github.com"
